/*
 * Genome Nexus API
 * This page shows how to use HTTP requests to access the Genome Nexus API. There are more high level clients available in Python, R, JavaScript, TypeScript and various other languages as well as a command line client to annotate MAF and VCF. See https://docs.genomenexus.org/api.  Aside from programmatic clients there are web based tools to annotate variants, see https://docs.genomenexus.org/tools.   We currently only provide long-term support for the '/annotation' endpoint. The other endpoints might change.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.genome_nexus.client;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SignalPopulationStats
 */
public class SignalPopulationStatsTest {
    private final SignalPopulationStats model = new SignalPopulationStats();

    /**
     * Model tests for SignalPopulationStats
     */
    @Test
    public void testSignalPopulationStats() {
        // TODO: test SignalPopulationStats
    }

    /**
     * Test the property 'afr'
     */
    @Test
    public void afrTest() {
        // TODO: test afr
    }

    /**
     * Test the property 'asj'
     */
    @Test
    public void asjTest() {
        // TODO: test asj
    }

    /**
     * Test the property 'asn'
     */
    @Test
    public void asnTest() {
        // TODO: test asn
    }

    /**
     * Test the property 'eur'
     */
    @Test
    public void eurTest() {
        // TODO: test eur
    }

    /**
     * Test the property 'impact'
     */
    @Test
    public void impactTest() {
        // TODO: test impact
    }

    /**
     * Test the property 'oth'
     */
    @Test
    public void othTest() {
        // TODO: test oth
    }

}
