/*
 * Genome Nexus API
 * This page shows how to use HTTP requests to access the Genome Nexus API. There are more high level clients available in Python, R, JavaScript, TypeScript and various other languages as well as a command line client to annotate MAF and VCF. See https://docs.genomenexus.org/api.  Aside from programmatic clients there are web based tools to annotate variants, see https://docs.genomenexus.org/tools.   We currently only provide long-term support for the '/annotation' endpoint. The other endpoints might change.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.genome_nexus.client;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.genome_nexus.client.GenomeNexusInfo;
import org.genome_nexus.client.SourceVersionInfo;
import org.genome_nexus.client.VEPInfo;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AggregateSourceInfo
 */
public class AggregateSourceInfoTest {
    private final AggregateSourceInfo model = new AggregateSourceInfo();

    /**
     * Model tests for AggregateSourceInfo
     */
    @Test
    public void testAggregateSourceInfo() {
        // TODO: test AggregateSourceInfo
    }

    /**
     * Test the property 'annotationSourcesInfo'
     */
    @Test
    public void annotationSourcesInfoTest() {
        // TODO: test annotationSourcesInfo
    }

    /**
     * Test the property 'genomeNexus'
     */
    @Test
    public void genomeNexusTest() {
        // TODO: test genomeNexus
    }

    /**
     * Test the property 'vep'
     */
    @Test
    public void vepTest() {
        // TODO: test vep
    }

}
