/*
 * Genome Nexus API
 * This page shows how to use HTTP requests to access the Genome Nexus API. There are more high level clients available in Python, R, JavaScript, TypeScript and various other languages as well as a command line client to annotate MAF and VCF. See https://docs.genomenexus.org/api.  Aside from programmatic clients there are web based tools to annotate variants, see https://docs.genomenexus.org/tools.   We currently only provide long-term support for the '/annotation' endpoint. The other endpoints might change.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.genome_nexus.client;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AlleleNumber
 */
public class AlleleNumberTest {
    private final AlleleNumber model = new AlleleNumber();

    /**
     * Model tests for AlleleNumber
     */
    @Test
    public void testAlleleNumber() {
        // TODO: test AlleleNumber
    }

    /**
     * Test the property 'an'
     */
    @Test
    public void anTest() {
        // TODO: test an
    }

    /**
     * Test the property 'anAfr'
     */
    @Test
    public void anAfrTest() {
        // TODO: test anAfr
    }

    /**
     * Test the property 'anAmr'
     */
    @Test
    public void anAmrTest() {
        // TODO: test anAmr
    }

    /**
     * Test the property 'anAsj'
     */
    @Test
    public void anAsjTest() {
        // TODO: test anAsj
    }

    /**
     * Test the property 'anEas'
     */
    @Test
    public void anEasTest() {
        // TODO: test anEas
    }

    /**
     * Test the property 'anFin'
     */
    @Test
    public void anFinTest() {
        // TODO: test anFin
    }

    /**
     * Test the property 'anNfe'
     */
    @Test
    public void anNfeTest() {
        // TODO: test anNfe
    }

    /**
     * Test the property 'anOth'
     */
    @Test
    public void anOthTest() {
        // TODO: test anOth
    }

    /**
     * Test the property 'anSas'
     */
    @Test
    public void anSasTest() {
        // TODO: test anSas
    }

}
