/*
 * Genome Nexus API
 * This page shows how to use HTTP requests to access the Genome Nexus API. There are more high level clients available in Python, R, JavaScript, TypeScript and various other languages as well as a command line client to annotate MAF and VCF. See https://docs.genomenexus.org/api.  Aside from programmatic clients there are web based tools to annotate variants, see https://docs.genomenexus.org/tools.   We currently only provide long-term support for the '/annotation' endpoint. The other endpoints might change.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.genome_nexus.client;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Clinvar
 */
public class ClinvarTest {
    private final Clinvar model = new Clinvar();

    /**
     * Model tests for Clinvar
     */
    @Test
    public void testClinvar() {
        // TODO: test Clinvar
    }

    /**
     * Test the property 'alternateAllele'
     */
    @Test
    public void alternateAlleleTest() {
        // TODO: test alternateAllele
    }

    /**
     * Test the property 'chromosome'
     */
    @Test
    public void chromosomeTest() {
        // TODO: test chromosome
    }

    /**
     * Test the property 'clinicalSignificance'
     */
    @Test
    public void clinicalSignificanceTest() {
        // TODO: test clinicalSignificance
    }

    /**
     * Test the property 'clinvarId'
     */
    @Test
    public void clinvarIdTest() {
        // TODO: test clinvarId
    }

    /**
     * Test the property 'conflictingClinicalSignificance'
     */
    @Test
    public void conflictingClinicalSignificanceTest() {
        // TODO: test conflictingClinicalSignificance
    }

    /**
     * Test the property 'endPosition'
     */
    @Test
    public void endPositionTest() {
        // TODO: test endPosition
    }

    /**
     * Test the property 'referenceAllele'
     */
    @Test
    public void referenceAlleleTest() {
        // TODO: test referenceAllele
    }

    /**
     * Test the property 'startPosition'
     */
    @Test
    public void startPositionTest() {
        // TODO: test startPosition
    }

}
