/*
 * Genome Nexus API
 * This page shows how to use HTTP requests to access the Genome Nexus API. There are more high level clients available in Python, R, JavaScript, TypeScript and various other languages as well as a command line client to annotate MAF and VCF. See https://docs.genomenexus.org/api.  Aside from programmatic clients there are web based tools to annotate variants, see https://docs.genomenexus.org/tools.   We currently only provide long-term support for the '/annotation' endpoint. The other endpoints might change.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.genome_nexus.client;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ColocatedVariant
 */
public class ColocatedVariantTest {
    private final ColocatedVariant model = new ColocatedVariant();

    /**
     * Model tests for ColocatedVariant
     */
    @Test
    public void testColocatedVariant() {
        // TODO: test ColocatedVariant
    }

    /**
     * Test the property 'dbSnpId'
     */
    @Test
    public void dbSnpIdTest() {
        // TODO: test dbSnpId
    }

    /**
     * Test the property 'gnomadNfeAllele'
     */
    @Test
    public void gnomadNfeAlleleTest() {
        // TODO: test gnomadNfeAllele
    }

    /**
     * Test the property 'gnomadNfeMaf'
     */
    @Test
    public void gnomadNfeMafTest() {
        // TODO: test gnomadNfeMaf
    }

    /**
     * Test the property 'gnomadAfrAllele'
     */
    @Test
    public void gnomadAfrAlleleTest() {
        // TODO: test gnomadAfrAllele
    }

    /**
     * Test the property 'gnomadAfrMaf'
     */
    @Test
    public void gnomadAfrMafTest() {
        // TODO: test gnomadAfrMaf
    }

    /**
     * Test the property 'gnomadEasAllele'
     */
    @Test
    public void gnomadEasAlleleTest() {
        // TODO: test gnomadEasAllele
    }

    /**
     * Test the property 'gnomadEasMaf'
     */
    @Test
    public void gnomadEasMafTest() {
        // TODO: test gnomadEasMaf
    }

}
