/*
 * Genome Nexus API
 * Genome Nexus Variant Annotation API
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.genome_nexus.client;

import org.genome_nexus.ApiException;
import org.genome_nexus.client.Version;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InfoControllerApi
 */
@Ignore
public class InfoControllerApiTest {

    private final InfoControllerApi api = new InfoControllerApi();

    
    /**
     * Retrieve Genome Nexus Version
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchVersionGETTest() throws ApiException {
        Version response = api.fetchVersionGET();

        // TODO: test validations
    }
    
}
