/*
 * Genome Nexus API
 * This page shows how to use HTTP requests to access the Genome Nexus API. There are more high level clients available in Python, R, JavaScript, TypeScript and various other languages as well as a command line client to annotate MAF and VCF. See https://docs.genomenexus.org/api.  Aside from programmatic clients there are web based tools to annotate variants, see https://docs.genomenexus.org/tools.   We currently only provide long-term support for the '/annotation' endpoint. The other endpoints might change.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.genome_nexus.client;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.genome_nexus.client.HrdScore;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for StatsByTumorType
 */
public class StatsByTumorTypeTest {
    private final StatsByTumorType model = new StatsByTumorType();

    /**
     * Model tests for StatsByTumorType
     */
    @Test
    public void testStatsByTumorType() {
        // TODO: test StatsByTumorType
    }

    /**
     * Test the property 'ageAtDx'
     */
    @Test
    public void ageAtDxTest() {
        // TODO: test ageAtDx
    }

    /**
     * Test the property 'fBiallelic'
     */
    @Test
    public void fBiallelicTest() {
        // TODO: test fBiallelic
    }

    /**
     * Test the property 'fCancerTypeCount'
     */
    @Test
    public void fCancerTypeCountTest() {
        // TODO: test fCancerTypeCount
    }

    /**
     * Test the property 'hrdScore'
     */
    @Test
    public void hrdScoreTest() {
        // TODO: test hrdScore
    }

    /**
     * Test the property 'msiScore'
     */
    @Test
    public void msiScoreTest() {
        // TODO: test msiScore
    }

    /**
     * Test the property 'nCancerTypeCount'
     */
    @Test
    public void nCancerTypeCountTest() {
        // TODO: test nCancerTypeCount
    }

    /**
     * Test the property 'numberOfGermlineHomozygous'
     */
    @Test
    public void numberOfGermlineHomozygousTest() {
        // TODO: test numberOfGermlineHomozygous
    }

    /**
     * Test the property 'numberWithSig'
     */
    @Test
    public void numberWithSigTest() {
        // TODO: test numberWithSig
    }

    /**
     * Test the property 'tmb'
     */
    @Test
    public void tmbTest() {
        // TODO: test tmb
    }

    /**
     * Test the property 'tumorType'
     */
    @Test
    public void tumorTypeTest() {
        // TODO: test tumorType
    }

}
